### ISSUE TITLE
Check post size to ensure < 75MB static content

### ISSUE THREAD

**Issue by tylerhm** [ucf-tower-app/mobile#125]
Post creation flow already works, so let's add some total content size checking.

**Comment by JakeSteinebronn** [comment]
`createPost` now throws if you attempt to make a post that's too large

**Comment by JakeSteinebronn** [comment]
We can discuss if we want to do anything further, but when you try to click createPost and it's too much storage, there's an error thrown by `createPost` which I believe is caught and `toast`ed (and this error message is descriptive enough, I think). Do we need to do anything else?

**Comment by tylerhm** [comment]
That sounds like enough feedback to me!
