### ISSUE TITLE
Users can toggle a profile setting BETA_SPOILERS

### ISSUE THREAD

**Issue by DanielW48** [ucf-tower-app/mobile#133]
- This hides content that is marked as a BETA_SPOILER and that the User HASN’T SENT (they can still see all content from routes that they have sent)
- Users can be prompted to enable this setting on their first entry into the app

### Tasks for this requirement:
- [ ] (devs fill in here with a link to your issues)
- [ ] 2
- [ ] 3

**Comment by Henry-Graves** [comment]
sends currently exist like this in the db, users don't have a list of sends: 
![image](https://user-images.githubusercontent.com/73561858/219717908-763f4263-4f63-49fa-bb83-a7df23aa1fb8.png)
----

**idea:**
- make checkUserSentRoute() on Xplat
- conditionally hide the content carousel where images/videos are if a user has no spoiler mode on
    - visible if user has sent that route

if no checkUserSentRoute(), just hide all content carousels until the user clicks through them. goofy UX but perhaps works for now
