### ISSUE TITLE
Employees can delete content from the Mobile interface

### ISSUE THREAD

**Issue by DanielW48** [ucf-tower-app/mobile#136]
No subtasks

**Comment by Henry-Graves** [comment]
see my xplat epic for backend implementation details & thought process: https://github.com/ucf-tower-app/xplat/issues/105 

The idea is that we'll have a main page where employees can see all active reports & take action on them.
Employees will also be able to see all modHistory as a log of previous actions taken, should probably be accessed through a button in the header of the active reports page.

**Comment by tylerhm** [comment]
> The idea is that we'll have a main page where employees can see all active reports & take action on them.

Just checking, I thought this functionality was only on web? We had originally planned to support nuking items from the media itself, but it seems like we are now adding full moderation queue functionality?

**Comment by DanielW48** [comment]
> > The idea is that we'll have a main page where employees can see all active reports & take action on them.
> 
> Just checking, I thought this functionality was only on web? We had originally planned to support nuking items from the media itself, but it seems like we are now adding full moderation queue functionality?

Indeed this is what we had planned. In the milestones, the only employee moderation action will be deleting posts/comments
