### ISSUE TITLE
Reject NSFW content client-side

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/mobile#170]
using a library like https://github.com/infinitered/nsfwjs, 93% accuracy with a 4.2MB model size
also can reject bad words with https://www.npmjs.com/package/bad-words

admittedly I haven't looked into either of these much, but we need to have something like this

- [x] #213 
- [x] #214

**Comment by tylerhm** [comment]
Bruh the hentai category though

pretty cool packages 👍🏼

**Comment by JakeSteinebronn** [comment]
tbh, this guy got caught with hentai on his laptop and he had to explain it by saying "uhhh I'm collecting data to train a nsfw filter yeah, i've never actually *looked* at this "
