### ISSUE TITLE
onScroll event won't work if initial load doesn't fill up screen

### ISSUE THREAD

**Issue by abrugal** [ucf-tower-app/mobile#189]
Currently our stride for initial load is 3. So if you go to your followers list it will load 3 followers, but if you have more you wont be able to load them because you can only perform the scroll event if the list is taking up the whole screen, which it isnt. 

An easy fix to this would be to make a stride specifically for each list, so for followers we make a stride that will cause the initial load to fill up the screen.

**Comment by JakeSteinebronn** [comment]
This no longer appears to be the case for flatlist. Can you confirm or deny this, and if so, close this issue as not planned? Thanks!

**Comment by abrugal** [comment]
Yeah flatlist seems to fix this issue. Closing
