### ISSUE TITLE
Viewing a profile with Posts crashes the app

### ISSUE THREAD

**Issue by abrugal** [ucf-tower-app/mobile#218]
Platform tested on: Android

Errors: 

![image](https://user-images.githubusercontent.com/5271307/219826575-8ac3a47d-72cf-4c1b-a62b-b6011f1a824b.png)

![image](https://user-images.githubusercontent.com/5271307/219826617-4d554a8f-ad01-4e23-b25b-9708700ff3b1.png)

**Comment by tylerhm** [comment]
Ran a bisect to find the bug. seems to be from this weird merge resolution commit.

```sh
f2e11f9f84aafdf1e13f1e65bd906cdd923fcbc4 is the first bad commit
commit f2e11f9f84aafdf1e13f1e65bd906cdd923fcbc4
Author: Esteban Brugal <estebancbrugal@gmail.com>
Date:   Thu Feb 16 23:25:55 2023 +0000

    Add back my send commits to this branch.
    Accidentally removed them after merging with main lol

 components/media/Send.tsx           |  85 +++++++++++++++++++++++++
 components/route/RouteLink.tsx      |  10 ++-
 screens/profile/Sends.tsx           | 122 ++++++++++++++++++++++++++++++++++--
 utils/routes/tabGlobal/paramList.ts |   4 +-
 4 files changed, 212 insertions(+), 9 deletions(-)
 create mode 100644 components/media/Send.tsx
```

**Comment by tylerhm** [comment]
Found the bug:
```tsx
p={noPadding ? '0' : this}
```
causes infinite recursion. Replacing `this` with '2' to fix for now. @abrugal feel free to push directly to main with the padding you actually intended here 👍🏼
