### ISSUE TITLE
home screen on no content loaded should display a message

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/mobile#249]
I made a new user & thought my home screen was just loading for a long time, but it was bc there was no content from users I'm following. 

We should display a message (also include the case where we fail to load content - no internet / fetch error) saying "failed to load content"

In my case this was bc our 3 default Tower users don't have any posts yet.

**Comment by JakeSteinebronn** [comment]
this probably doesn't actually need to happen, since in just a short time there will at least be messages from tower setters

**Comment by abrugal** [comment]
I think we should still show something if its empty for some reason. since it would be very easy

**Comment by JakeSteinebronn** [comment]
I mean sure, but in general, if it's empty, there's an issue
