### ISSUE TITLE
Send Post info can get smushed (horizontal padding)

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/mobile#264]
look at Jacob’s send post below, the time stamp gets cramped

![DF8DB4CE-99C8-4166-9E65-EEBC9A5EAAA1](https://user-images.githubusercontent.com/73561858/221702131-1466e526-38e2-4cda-9fb8-768a04ae1122.jpeg)

**Comment by JakeSteinebronn** [comment]
duplicate, already handled
