### ISSUE TITLE
Fully support dark mode

### ISSUE THREAD

**Issue by tylerhm** [ucf-tower-app/mobile#284]
Dark mode superior. Reference this issue in all dark-mode related commits

**Comment by JakeSteinebronn** [comment]
Have we noticed there's weird stuff around context menus and such?

**Comment by tylerhm** [comment]
> Have we noticed there's weird stuff around context menus and such?

Fixed in #286 , thanks for the catch.

**Comment by tylerhm** [comment]
Why not planned?

**Comment by JakeSteinebronn** [comment]
oh balls I thought I made a separate issue for the dark mode bug not that i'd commented on the existing mb

**Comment by abrugal** [comment]
The timestampt in the sent button is very dark

![Screenshot_20230311_192221_Expo Go](https://user-images.githubusercontent.com/5271307/224517531-b4373953-877b-4a8f-bf26-569f83b1a376.jpg)

The text cursor is very dark, barely noticeable, seems to be the same color in all text boxes

![Screenshot_20230311_192409_Expo Go](https://user-images.githubusercontent.com/5271307/224517557-5a677819-7c50-4942-857e-e6a23b6e58a6.jpg)
