### ISSUE TITLE
React Navigation

### ISSUE THREAD

**Issue by abrugal** [ucf-tower-app/mobile#30]
I decided I would work on the skeleton for the actual Leaderboards Screen and add functionality to change to the other leaderboard screens. My plan was to use the navigation function as a prop to navigate between the screen. But I got a type error due to typescript. So I looked up how to do it properly. These are the websites I read. 

https://javascript.plainenglish.io/react-navigation-v6-with-typescript-nested-navigation-part-2-87844f643e37
https://reactnavigation.org/docs/typescript/#nesting-navigators
https://reactnavigation.org/docs/typescript/#organizing-types

I've implemented all of this in a separate branch.

Also we need to decide what tabs actually need a stack navigator nested in them. For example, I dont think the Active Routes Tab will need a Stack inside of it. Same for the Home Screen.

**Comment by TylerMathis** [comment]
> Also we need to decide what tabs actually need a stack navigator nested in them. For example, I dont think the Active Routes Tab will need a Stack inside of it. Same for the Home Screen.
This is true, but I'm not sure if the added complexity of removing the Stack Navigator for some screens is worth it. Just because we have the navigator active doesn't mean we have to use it 🤷🏼

**Comment by abrugal** [comment]
I dont think it would be complex, I think it would make things much more simpler. For example, if we removed Active Routes Stack then we could remove the whole utils/routes/activeRoutes folder, since the component would just go in the component of the ActiveRoutes tab.

**Comment by TylerMathis** [comment]
Yeah that is fair, but I think it would be best to keep them around in case we find ourselves wanting the functionality down the line. Would be annoying to add them back in. What are your thoughts?

Also in regards to https://github.com/ucf-tower-app/mobile/commit/f65432a2d2a3df0c9285c3eed39e2d4678406c7f, we can definitely remove the code duplication and integrate with the old generic loop. Have you tried creating a list of Stacks and their respective route maps? You could then iterate over that instead of the simple tab map like before.

**Comment by abrugal** [comment]
Ahhhh list of stacks could work. Let me try

**Comment by TylerMathis** [comment]
Awesome!

**Comment by abrugal** [comment]
> Yeah that is fair, but I think it would be best to keep them around in case we find ourselves wanting the functionality down the line. Would be annoying to add them back in. What are your thoughts?

Yeah adding it back would be annoying. We can keep it and can decide if we'll remove once we know for sure what our screens will have and need.
