### ISSUE TITLE
verified user (status=1, non-ucf) can view their profile through Leaderboard page

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/mobile#317]
We removed the home row button for a user's own profile if they're only verified, but they can still access their own profile if they click on their card in the leaderboard tab.

For consistency, I think we should add the home row profile button back, or not make their profile card clickable if they're only verified.

**IMO the best way to do it is re-add the profile button & show a popup recommending that they upgrade to a UCF email or ask for approval in order to post.**

**Comment by tylerhm** [comment]
Related to #81

**Comment by tylerhm** [comment]
I agree with your solution. We should show the profile, and then a little message saying "Verify your knights email to post!"
