### ISSUE TITLE
Trying to implement triple nested navigation

### ISSUE THREAD

**Issue by abrugal** [ucf-tower-app/mobile#40]
I wanted to try to implement a triple nested navigation structure because there are screens that shouldn't have the bottom tab shown. For example, the Login Screen and Sign Up Screen shouldn't have a bottom tab.

For some reason when creating a triple nested navigator like this RootStack -> Tabs -> Stack, it breaks when switching tabs due to this piece of code. I thought this was because there were triple nested navigators and the app just couldn't handle it. But after slowly removing code I figured out it was due to this.

![image](https://user-images.githubusercontent.com/5271307/211207863-dd857aad-163a-45ab-a797-9da4ff515396.png)

Specifically the fact that the return is nested within another return is what breaks it. And the reason we have this nested return is to pass in the parameters to the buildStack function and not get the error from the component line in a Screen saying that it requires a React Component. 

![image](https://user-images.githubusercontent.com/5271307/211208389-856e8e3b-10de-4077-9b91-5602a5c58fa6.png)

Here they talk about how to properly pass in props to a screen: https://reactnavigation.org/docs/hello-react-navigation#passing-additional-props

So we could do this (specifically option 1), or just manually type in the code for each tab's stack. 

What do you think @TylerMathis ? What do you think about implementing a triple nested navigation structure. There are ways to remove the bottom tab for specific screens, but it seems kind've hard to implement, I tried to do it and couldn't really get it to work.

**Comment by TylerMathis** [comment]
Lets hop on a VC to talk about this.

**Comment by abrugal** [comment]
After talking we decided to implement the triple nested structure.
