### ISSUE TITLE
Users profile header will show their personal best stats (top rope/boulder highest grades)

### ISSUE THREAD

**Issue by Henry-Graves** [ucf-tower-app/mobile#74]
It could also show total sends, ... etc other stats, I don't think the design is solidified yet.

### Tasks for this requirement:
- [ ] (devs fill in here with a link to your issues)
- [ ] 2
- [ ] 3

**Comment by JakeSteinebronn** [comment]
is this done? I think @abrugal did this ages ago

**Comment by abrugal** [comment]
Yeah this is done
